# Generated by Django 5.1.6 on 2025-03-01 22:43

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Nice_Habit",
            fields=[
                (
                    "action",
                    models.CharField(
                        max_length=150, verbose_name="Действие приятной привычки"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True, verbose_name="Признак публичности"
                    ),
                ),
                (
                    "is_nice",
                    models.BooleanField(
                        default=True, verbose_name="Признак приятной привычки"
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель приятной привычки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Приятная привычка",
                "verbose_name_plural": "Приятные привычки",
                "ordering": ["action"],
            },
        ),
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "place",
                    models.CharField(
                        max_length=150, verbose_name="Место выполнения привычки"
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        default=datetime.time(0, 0),
                        help_text="00:00:00",
                        verbose_name="Время выполнения привычки",
                    ),
                ),
                ("action", models.CharField(max_length=150, verbose_name="Действие")),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Вознаграждение за выполнение",
                    ),
                ),
                (
                    "execution_time",
                    models.DurationField(
                        default=datetime.timedelta(seconds=120),
                        help_text="00:00:00",
                        verbose_name="Время на выполнение привычки",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True, verbose_name="Признак публичности"
                    ),
                ),
                (
                    "days_of_week",
                    models.CharField(
                        default="пн, вт, ср, чт, пт, сб, вс",
                        help_text="Введите дни недели через запятую (например, 'пн, вт, ср'), по умолчанию: ежедневно",
                        max_length=100,
                        verbose_name="Дни недели",
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель привычки",
                    ),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_habits",
                        to="tracker.nice_habit",
                        verbose_name="Связанная приятная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
                "ordering": ["action"],
            },
        ),
    ]
