# Generated by Django 5.1.6 on 2025-02-15 15:17

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=150, verbose_name="Название привычки"),
                ),
                (
                    "place",
                    models.CharField(
                        max_length=150, verbose_name="Место выполнения привычки"
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        default=datetime.time(0, 0),
                        verbose_name="Время, когда необходимо выполнять привычку",
                    ),
                ),
                ("action", models.CharField(max_length=150, verbose_name="Действие")),
                (
                    "is_nice_habit",
                    models.BooleanField(
                        default=False, verbose_name="Признак приятной привычки"
                    ),
                ),
                (
                    "period",
                    models.IntegerField(
                        blank=True,
                        default=1,
                        null=True,
                        verbose_name="Период выполнения (в днях)",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Вознаграждение за выполнение",
                    ),
                ),
                (
                    "execution_time",
                    models.TimeField(
                        default=(0, 2), verbose_name="Время выполнения привычки"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True, verbose_name="Признак публичности"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель привычки",
                    ),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_habits",
                        to="tracker.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
                "ordering": ["title"],
            },
        ),
    ]
