# Generated by Django 5.1.6 on 2025-02-15 15:40

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habit",
            options={
                "ordering": ["action"],
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
        migrations.RemoveField(
            model_name="habit",
            name="is_nice_habit",
        ),
        migrations.RemoveField(
            model_name="habit",
            name="title",
        ),
        migrations.AlterField(
            model_name="habit",
            name="execution_time",
            field=models.TimeField(
                default=(0, 2), verbose_name="Время на выполнение привычки"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.TimeField(
                default=datetime.time(0, 0), verbose_name="Время выполнения привычки"
            ),
        ),
        migrations.CreateModel(
            name="Nice_Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        max_length=150, verbose_name="Действие приятной привычки"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True, verbose_name="Признак публичности"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель приятной привычки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Приятная привычка",
                "verbose_name_plural": "Приятные привычки",
                "ordering": ["action"],
            },
        ),
        migrations.AlterField(
            model_name="habit",
            name="related_habit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_habits",
                to="tracker.nice_habit",
                verbose_name="Связанная приятная привычка",
            ),
        ),
    ]
