# Generated by Django 5.1.6 on 2025-02-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_alter_habit_options_remove_habit_is_nice_habit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nice_habit",
            name="is_nice",
            field=models.BooleanField(
                default=True, verbose_name="Признак приятной привычки"
            ),
        ),
    ]
