# Generated by Django 5.1.6 on 2025-02-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_nice_habit_is_nice"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="last_performed",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Поле для хранения даты последнего выполнения",
            ),
        ),
    ]
