# Generated by Django 5.1.6 on 2025-02-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0004_habit_last_performed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="last_performed",
            field=models.DateField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="Поле для хранения даты последнего выполнения",
            ),
        ),
    ]
