# Generated by Django 5.1.6 on 2025-02-16 15:09

from django.db import migrations, models

import tracker.models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0005_alter_habit_last_performed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="execution_time",
            field=models.TimeField(
                default=tracker.models.default_time_2,
                verbose_name="Время на выполнение привычки",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.TimeField(
                default=tracker.models.default_time_0,
                verbose_name="Время выполнения привычки",
            ),
        ),
    ]
