# Generated by Django 5.1.6 on 2025-02-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0006_alter_habit_execution_time_alter_habit_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="period",
            field=models.IntegerField(
                blank=True,
                default=1,
                null=True,
                verbose_name="Период выполнения (в днях), 1 - ежедневно",
            ),
        ),
    ]
