# Generated by Django 5.1.6 on 2025-02-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0007_alter_habit_period"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="last_performed",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="Поле для хранения времени и даты последнего выполнения",
            ),
        ),
    ]
