# Generated by Django 5.1.6 on 2025-02-19 19:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0009_habit_days_of_week"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="days_of_week",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("Monday", "Понедельник"),
                        ("Tuesday", "Вторник"),
                        ("Wednesday", "Среда"),
                        ("Thursday", "Четверг"),
                        ("Friday", "Пятница"),
                        ("Saturday", "Суббота"),
                        ("Sunday", "Воскресенье"),
                    ],
                    max_length=100,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
