# Generated by Django 5.1.6 on 2025-02-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0010_alter_habit_days_of_week"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habit",
            name="last_performed",
        ),
        migrations.AlterField(
            model_name="habit",
            name="days_of_week",
            field=models.CharField(
                blank=True,
                help_text="Введите дни недели через запятую (например, 'пн, вт, ср')",
                max_length=100,
                null=True,
                verbose_name="Дни недели",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="period",
            field=models.IntegerField(
                blank=True,
                default=7,
                null=True,
                verbose_name="Период выполнения (в днях), 7 - ежедневно",
            ),
        ),
    ]
