# Generated by Django 5.1.6 on 2025-02-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tracker",
            "0011_remove_habit_last_performed_alter_habit_days_of_week_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="nice_habit",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
